[build]
  publish = "static"
  command = "bash ./netlify-build.sh"

[build.environment]
  NODE_VERSION = "16"

[functions]
  directory = "netlify/functions"

# Simplified redirects
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Add headers for CSS files
[[headers]]
  for = "/static/css/*"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=3600"

# Add headers for JS files
[[headers]]
  for = "/static/js/*"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=3600" 