[build]
  publish = "static"
  command = "bash ./netlify-build.sh"

[build.environment]
  PYTHON_VERSION = "3.9"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 