[build]
  publish = "static"
  command = "mkdir -p static && cp -r static/css static/ && cp -r static/js static/ && cp -r templates/index.html static/index.html"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 